# Generated by Django 2.2.24 on 2021-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.CharField(max_length=100)),
                ('cut', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('clarity', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('z', models.CharField(max_length=100)),
            ],
        ),
    ]
