# Generated by Django 2.2.24 on 2021-07-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diamond',
            new_name='CsvFile',
        ),
    ]
